// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseFormInput: typeof import('./src/components/BaseFormInput.vue')['default']
    BaseFormMessage: typeof import('./src/components/BaseFormMessage.vue')['default']
    BaseFormOne: typeof import('./src/components/BaseFormOne.vue')['default']
    BaseFormSelect: typeof import('./src/components/BaseFormSelect.vue')['default']
    BaseFormTextarea: typeof import('./src/components/BaseFormTextarea.vue')['default']
    BaseFormThree: typeof import('./src/components/BaseFormThree.vue')['default']
    BaseFormTwo: typeof import('./src/components/BaseFormTwo.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseMessage: typeof import('./src/components/BaseMessage.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseRate: typeof import('./src/components/BaseRate.vue')['default']
    BaseScore: typeof import('./src/components/BaseScore.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseSvgIcon: typeof import('./src/components/BaseSvgIcon.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    BaseTag: typeof import('./src/components/BaseTag.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    BaseToast: typeof import('./src/components/BaseToast.vue')['default']
    copy: typeof import('./src/components/EmployeeStaffMain copy.vue')['default']
    EmployeeLeaderCreate: typeof import('./src/components/EmployeeLeaderCreate.vue')['default']
    EmployeeLeaderMain: typeof import('./src/components/EmployeeLeaderMain.vue')['default']
    EmployeeLeaderUpdate: typeof import('./src/components/EmployeeLeaderUpdate.vue')['default']
    EmployeeResultFilter: typeof import('./src/components/EmployeeResultFilter.vue')['default']
    EmployeeResultMain: typeof import('./src/components/EmployeeResultMain.vue')['default']
    EmployeeStaffCreate: typeof import('./src/components/EmployeeStaffCreate.vue')['default']
    EmployeeStaffEdit: typeof import('./src/components/EmployeeStaffEdit.vue')['default']
    EmployeeStaffMain: typeof import('./src/components/EmployeeStaffMain.vue')['default']
    EmployeeStaffRead: typeof import('./src/components/EmployeeStaffRead.vue')['default']
    EmployeeStaffUpdate: typeof import('./src/components/EmployeeStaffUpdate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
    TheModal: typeof import('./src/components/TheModal.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheSideBar: typeof import('./src/components/TheSideBar.vue')['default']
  }
}
