// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminListCard: typeof import('./src/components/AdminListCard.vue')['default']
    AdminListMain: typeof import('./src/components/AdminListMain.vue')['default']
    AdminQuestionAnswer: typeof import('./src/components/AdminQuestionAnswer.vue')['default']
    AdminQuestionMain: typeof import('./src/components/AdminQuestionMain.vue')['default']
    AdminResultsMain: typeof import('./src/components/AdminResultsMain.vue')['default']
    AdminUsersMain: typeof import('./src/components/AdminUsersMain.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseConfirm: typeof import('./src/components/BaseConfirm.vue')['default']
    BaseFormInput: typeof import('./src/components/BaseFormInput.vue')['default']
    BaseFormScore: typeof import('./src/components/BaseFormScore.vue')['default']
    BaseFormSelect: typeof import('./src/components/BaseFormSelect.vue')['default']
    BaseFormTag: typeof import('./src/components/BaseFormTag.vue')['default']
    BaseFormTextarea: typeof import('./src/components/BaseFormTextarea.vue')['default']
    BaseFormThree: typeof import('./src/components/BaseFormThree.vue')['default']
    BaseFormTwo: typeof import('./src/components/BaseFormTwo.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseMessage: typeof import('./src/components/BaseMessage.vue')['default']
    BaseQuestionFormAll: typeof import('./src/components/BaseQuestionFormAll.vue')['default']
    BaseQuestionFormScore: typeof import('./src/components/BaseQuestionFormScore.vue')['default']
    BaseQuestionFormText: typeof import('./src/components/BaseQuestionFormText.vue')['default']
    BaseScore: typeof import('./src/components/BaseScore.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseSvgIcon: typeof import('./src/components/BaseSvgIcon.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    BaseTag: typeof import('./src/components/BaseTag.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    BaseToast: typeof import('./src/components/BaseToast.vue')['default']
    copy: typeof import('./src/components/AdminQuestionAnswer copy.vue')['default']
    EmployeeAnswer: typeof import('./src/components/EmployeeAnswer.vue')['default']
    EmployeeLeaderMain: typeof import('./src/components/EmployeeLeaderMain.vue')['default']
    EmployeeResultMain: typeof import('./src/components/EmployeeResultMain.vue')['default']
    EmployeeStaffAnswer: typeof import('./src/components/EmployeeStaffAnswer.vue')['default']
    EmployeeStaffMain: typeof import('./src/components/EmployeeStaffMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLoading: typeof import('./src/components/TheLoading.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
    TheModal: typeof import('./src/components/TheModal.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheSideBar: typeof import('./src/components/TheSideBar.vue')['default']
  }
}
